debug: true

# DJANGO ALLOWED_HOSTS
hosts:
  - 127.0.0.1
  - localhost
  - {{ project_name }}

common:
  secret_key: "{{ secret_key }}"

# DJANGO DATABASE SETTINGS
db:
  engine: django.db.backends.postgresql
  host: postgres
  port: 5432
  name: {{ project_name }}
  user: {{ project_name }}
  password: {{ project_name }}

# CACHES
caches:
  redis:
    location:
      - redis:6379
    options:
      db: 0
      max_connections: 1000
      connection_pool_class_kwargs:
        max_connections: 50
        timeout: 20
