debug: true

# DJANGO ALLOWED_HOSTS
hosts:
  - 127.0.0.1
  - localhost

common:
  secret_key: "{{ secret_key }}"

# DJANGO DATABASE SETTINGS
db:
  engine: django.db.backends.postgresql
  host: 127.0.0.1
  port: 5432
  name: {{ project_name }}
  user: {{ project_name }}
  password: {{ project_name }}

# CACHES
caches:
  redis:
    location:
      - 127.0.0.1:6379
    options:
      db: 0
      max_connections: 1000
      connection_pool_class_kwargs:
        max_connections: 50
        timeout: 20

celery:
  broker_url: "redis://localhost:6379/0"
  result_backend: "redis://localhost:6379/1"
  workers: 1
